name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    services:
      postgresql:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        image: postgres
        ports:
          - 5433:5432
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
      temporal:
        env:
          DB: postgresql
          DB_PORT: 5433
          POSTGRES_USER: postgres
          POSTGRES_PWD: postgres
          POSTGRES_SEEDS: postgresql
        image: temporalio/auto-setup:1.18.4
        ports:
          - 7233:7233

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn

      - run: yarn build
    
      - run: yarn test:e2e